spring:
    application:
        name: ${project.artifactId}

thematic:
    datasource:
        name: hibernate.oracle.cfg.xml

logging:
    level:
        root: ERROR
        com.yulintu.thematic.data.ServiceAdvicesTracker: WARN
